### ISSUE TITLE
Error during template rendering: hooyarshahidi.herokuapp.com

### ISSUE THREAD

**Issue by BaseMax** [Hooyarsh/portfolio-project#1]
### ProgrammingError at /

> relation "jobs_job" does not exist
LINE 1: ...d", "jobs_job"."image", "jobs_job"."summary" FROM "jobs_job"

### Error during template rendering

> In template /app/jobs/templates/jobs/home.html, error at line 58
relation "jobs_job" does not exist LINE 1: ...d", "jobs_job"."image", "jobs_job"."summary" FROM "jobs_job" ^

```
48 	        </p>
49 	        <img src="{% static 'hooyar2.jpg' %}" height="300" />
50 	      </div>
51 	    </section>
52 	
53 	    <div class="album py-5 bg-light">
54 	      <div class="container">
55 	
56 	        <div class="row">
57 	
58 	          {% for job in jobs.all %}
```

![2021-09-05](https://user-images.githubusercontent.com/2658040/132118411-91f72c21-e875-43ea-b5e3-f5fa29961f31.png)

**Comment by Hooyarsh** [comment]
yeah, I know about it. I will try to fix it like in a month or two.
